### ISSUE TITLE
Add custom code event to "forgot" operation

### ISSUE THREAD

**Issue by silviubogan** [jillix/login#10]
A new event should be added to the `forgot` operation like in the `getUserInfo` function for custom code execution as a handler of this event. An example usage would be in the [GaragePlus 2.0 PartnerLogin (partnerlogin-gp)](https://bitbucket.org/jillix/partnerlogin-gp) project from BitBucket where this is needed for fixing [this bug](https://bitbucket.org/jillix/partnerlogin-gp/issue/41/block-login-for-non-ak-customers) because the check for the AK status of the user should also be done in the `forget` operation and this is code specific to the application project and should not be added to the login module.

**Comment by gabipetrovay** [comment]
Fixes between b03e21e18701e025ee42be132a1771f9e5a361d4 and 8be867bfdf58348ce0630b767c7262cb6b9eaf99
